apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-pre-sync
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      initContainers:
      - name: terraform-plan
        image: localhost:5000/sos/poc-bill-of-materials:latest
        command:
          - terraform
          - plan
      - name: terraform-apply
        image: localhost:5000/sos/poc-bill-of-materials:latest
        command:
          - terraform
          - apply
          - -auto-approve
      - name: ansible-job
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
          - echo 'Ansible job run here'
      containers:
      - name: finally
        image: busybox:1.28
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - -c
          - echo 'This means the whole thing is now done'
      restartPolicy: Never
  backoffLimit: 2
