apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-pre-sync
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: terraform-plan
        image: localhost:5000/sos/poc-bill-of-materials:latest
        command:
          - "terraform"
          - "plan"
          - "nothing that works goes here to fail"
      restartPolicy: Never
  backoffLimit: 2
